// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 FireBall1725 (Adaléa)

package models

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// Stable kind strings used across the AI metadata enrichment surface. Free-form
// strings (no enum) so we can add operations without a schema migration.
const (
	AIMetaKindDescriptionClean = "description_clean"
	AIMetaKindSeriesMetadata   = "series_metadata"
	AIMetaKindSeriesArcs       = "series_arcs"

	AIMetaTargetBook   = "book"
	AIMetaTargetSeries = "series"

	AIMetaRunStatusRunning   = "running"
	AIMetaRunStatusCompleted = "completed"
	AIMetaRunStatusFailed    = "failed"
	AIMetaRunStatusSkipped   = "skipped"

	AIMetaProposalStatusPending            = "pending"
	AIMetaProposalStatusAccepted           = "accepted"
	AIMetaProposalStatusRejected           = "rejected"
	AIMetaProposalStatusPartiallyAccepted  = "partially_accepted"
)

// AIMetadataRun is one AI call recorded for audit + cost accounting +
// jobs-UI inspection. Prompt and ResponseText are stored inline so the run
// detail panel can expand them without joining a separate events table.
type AIMetadataRun struct {
	ID               uuid.UUID  `json:"id"`
	LibraryID        *uuid.UUID `json:"library_id"`
	JobID            *uuid.UUID `json:"job_id"`
	TriggeredBy      *uuid.UUID `json:"triggered_by"`
	Kind             string     `json:"kind"`
	TargetType       string     `json:"target_type"`
	TargetID         uuid.UUID  `json:"target_id"`
	ProviderType     string     `json:"provider_type"`
	ModelID          string     `json:"model_id"`
	Status           string     `json:"status"`
	Error            string     `json:"error"`
	TokensIn         int        `json:"tokens_in"`
	TokensOut        int        `json:"tokens_out"`
	EstimatedCostUSD float64    `json:"estimated_cost_usd"`
	Prompt           string     `json:"prompt"`
	ResponseText     string     `json:"response_text"`
	StartedAt        time.Time  `json:"started_at"`
	FinishedAt       *time.Time `json:"finished_at"`
}

// AIMetadataProposal holds the suggestion payload generated by SuggestSeries*
// operations. Pending proposals show up in the series detail review panel; the
// user accepts / rejects per-field or per-arc and the accept action writes
// the chosen subset onto the series.
type AIMetadataProposal struct {
	ID         uuid.UUID       `json:"id"`
	LibraryID  uuid.UUID       `json:"library_id"`
	RunID      *uuid.UUID      `json:"run_id"`
	TargetType string          `json:"target_type"`
	TargetID   uuid.UUID       `json:"target_id"`
	Kind       string          `json:"kind"`
	Payload    json.RawMessage `json:"payload"`
	Status     string          `json:"status"`
	CreatedAt  time.Time       `json:"created_at"`
	AppliedAt  *time.Time      `json:"applied_at"`
	AppliedBy  *uuid.UUID      `json:"applied_by"`
}

// SeriesMetadataPayload is the shape persisted for kind=series_metadata
// proposals. Each field is optional — the AI may have evidence for some and
// not others. Genres is always non-nil but may be empty.
type SeriesMetadataPayload struct {
	Status      *string  `json:"status,omitempty"`       // ongoing | completed | hiatus | cancelled
	TotalCount  *int     `json:"total_count,omitempty"`
	Demographic *string  `json:"demographic,omitempty"`  // shounen | seinen | shoujo | josei | etc
	Genres      []string `json:"genres"`
	Description *string  `json:"description,omitempty"`  // cleaned-up description
}

// SeriesArcsPayload is the shape persisted for kind=series_arcs proposals.
// Each arc is independently acceptable; the accept endpoint takes a list of
// indices to apply.
type SeriesArcsPayload struct {
	Arcs []ProposedArc `json:"arcs"`
}

type ProposedArc struct {
	Name     string `json:"name"`
	Position int    `json:"position"`
	VolStart *int   `json:"vol_start,omitempty"`
	VolEnd   *int   `json:"vol_end,omitempty"`
}
